INSERT INTO book (ISBN, title, author, genre, amount) VALUES
(UUID(), 'Becoming', 'Michelle Obama', 'Memoir', 200),
(UUID(), 'Where the Crawdads Sing', 'Delia Owens', 'Fiction', 150),
(UUID(), 'Educated', 'Tara Westover', 'Memoir', 180),
(UUID(), 'The Testaments', 'Margaret Atwood', 'Fiction', 170),
(UUID(), 'Little Fires Everywhere', 'Celeste Ng', 'Fiction', 160),
(UUID(), 'Circe', 'Madeline Miller', 'Fantasy', 190),
(UUID(), 'The Silent Patient', 'Alex Michaelides', 'Thriller', 170),
(UUID(), 'The Dutch House', 'Ann Patchett', 'Fiction', 150),
(UUID(), 'The Nickel Boys', 'Colson Whitehead', 'Fiction', 180),
(UUID(), 'Normal People', 'Sally Rooney', 'Fiction', 160),
(UUID(), 'Daisy Jones & The Six', 'Taylor Jenkins Reid', 'Fiction', 190),
(UUID(), 'City of Girls', 'Elizabeth Gilbert', 'Fiction', 170),
(UUID(), 'Where''d You Go, Bernadette', 'Maria Semple', 'Fiction', 150),
(UUID(), 'The Goldfinch', 'Donna Tartt', 'Fiction', 180),
(UUID(), 'To Kill a Mockingbird', 'Harper Lee', 'Fiction', 200),
(UUID(), 'The Great Gatsby', 'F. Scott Fitzgerald', 'Fiction', 220),
(UUID(), '1984', 'George Orwell', 'Science Fiction', 210),
(UUID(), 'The Catcher in the Rye', 'J.D. Salinger', 'Fiction', 230),
(UUID(), 'Animal Farm', 'George Orwell', 'Fiction', 240),
(UUID(), 'Lord of the Flies', 'William Golding', 'Fiction', 250),
(UUID(), 'Brave New World', 'Aldous Huxley', 'Science Fiction', 260),
(UUID(), 'Fahrenheit 451', 'Ray Bradbury', 'Science Fiction', 270),
(UUID(), 'The Handmaid''s Tale', 'Margaret Atwood', 'Science Fiction', 280),
(UUID(), 'The Alchemist', 'Paulo Coelho', 'Fiction', 290),
(UUID(), 'The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 300),
(UUID(), 'The Fellowship of the Ring', 'J.R.R. Tolkien', 'Fantasy', 310),
(UUID(), 'The Two Towers', 'J.R.R. Tolkien', 'Fantasy', 320),
(UUID(), 'The Return of the King', 'J.R.R. Tolkien', 'Fantasy', 330),
(UUID(), 'Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'Fantasy', 340),
(UUID(), 'Harry Potter and the Chamber of Secrets', 'J.K. Rowling', 'Fantasy', 350),
(UUID(), 'Harry Potter and the Prisoner of Azkaban', 'J.K. Rowling', 'Fantasy', 360),
(UUID(), 'Harry Potter and the Goblet of Fire', 'J.K. Rowling', 'Fantasy', 370),
(UUID(), 'Harry Potter and the Order of the Phoenix', 'J.K. Rowling', 'Fantasy', 380),
(UUID(), 'Harry Potter and the Half-Blood Prince', 'J.K. Rowling', 'Fantasy', 390),
(UUID(), 'Harry Potter and the Deathly Hallows', 'J.K. Rowling', 'Fantasy', 400),
(UUID(), 'The Da Vinci Code', 'Dan Brown', 'Thriller', 410),
(UUID(), 'Angels & Demons', 'Dan Brown', 'Thriller', 420),
(UUID(), 'Inferno', 'Dan Brown', 'Thriller', 430),
(UUID(), 'Origin', 'Dan Brown', 'Thriller', 440),
(UUID(), 'Digital Fortress', 'Dan Brown', 'Thriller', 450),
(UUID(), 'The Lost Symbol', 'Dan Brown', 'Thriller', 460),
(UUID(), 'The Girl with the Dragon Tattoo', 'Stieg Larsson', 'Thriller', 470),
(UUID(), 'The Girl Who Played with Fire', 'Stieg Larsson', 'Thriller', 480),
(UUID(), 'The Girl Who Kicked the Hornet''s Nest', 'Stieg Larsson', 'Thriller', 490),
(UUID(), 'Gone Girl', 'Gillian Flynn', 'Thriller', 500),
(UUID(), 'The Girl on the Train', 'Paula Hawkins', 'Thriller', 510),
(UUID(), 'Sharp Objects', 'Gillian Flynn', 'Thriller', 520),
(UUID(), 'Dark Places', 'Gillian Flynn', 'Thriller', 530),
(UUID(), 'The Hunger Games', 'Suzanne Collins', 'Science Fiction', 540),
(UUID(), 'Catching Fire', 'Suzanne Collins', 'Science Fiction', 550),
(UUID(), 'Mockingjay', 'Suzanne Collins', 'Science Fiction', 560),
(UUID(), 'The Help', 'Kathryn Stockett', 'Fiction', 570),
(UUID(), 'The Fault in Our Stars', 'John Green', 'Fiction', 580),
(UUID(), 'The Maze Runner', 'James Dashner', 'Science Fiction', 590),
(UUID(), 'The Scorch Trials', 'James Dashner', 'Science Fiction', 600),
(UUID(), 'The Death Cure', 'James Dashner', 'Science Fiction', 610),
(UUID(), 'The Book Thief', 'Markus Zusak', 'Fiction', 620),
(UUID(), 'A Game of Thrones', 'George R.R. Martin', 'Fantasy', 630),
(UUID(), 'A Clash of Kings', 'George R.R. Martin', 'Fantasy', 640),
(UUID(), 'A Storm of Swords', 'George R.R. Martin', 'Fantasy', 650),
(UUID(), 'A Feast for Crows', 'George R.R. Martin', 'Fantasy', 660),
(UUID(), 'A Dance with Dragons', 'George R.R. Martin', 'Fantasy', 670),
(UUID(), 'The Name of the Wind', 'Patrick Rothfuss', 'Fantasy', 680),
(UUID(), 'The Wise Man''s Fear', 'Patrick Rothfuss', 'Fantasy', 690),
(UUID(), 'The Slow Regard of Silent Things', 'Patrick Rothfuss', 'Fantasy', 700),
(UUID(), 'The Way of Kings', 'Brandon Sanderson', 'Fantasy', 710),
(UUID(), 'Words of Radiance', 'Brandon Sanderson', 'Fantasy', 720),
(UUID(), 'Oathbringer', 'Brandon Sanderson', 'Fantasy', 730),
(UUID(), 'Rhythm of War', 'Brandon Sanderson', 'Fantasy', 740),
(UUID(), 'The Final Empire', 'Brandon Sanderson', 'Fantasy', 750),
(UUID(), 'The Well of Ascension', 'Brandon Sanderson', 'Fantasy', 760),
(UUID(), 'The Hero of Ages', 'Brandon Sanderson', 'Fantasy', 770),
(UUID(), 'Warbreaker', 'Brandon Sanderson', 'Fantasy', 780),
(UUID(), 'Elantris', 'Brandon Sanderson', 'Fantasy', 790),
(UUID(), 'Mistborn: The Alloy of Law', 'Brandon Sanderson', 'Fantasy', 800),
(UUID(), 'Mistborn: Shadows of Self', 'Brandon Sanderson', 'Fantasy', 810),
(UUID(), 'Mistborn: The Bands of Mourning', 'Brandon Sanderson', 'Fantasy', 820);

